# Latent Factor Model(LFM) Gradient Descent

In [43]:
import numpy as np

"""
@输入参数：
R：U*I 的评分矩阵
K：隐特征向量维度数量
max_iter: 最大迭代次数
alpha：步长
lamda：正则化系数

@输出：
分解之后的 P，Q
P：初始化用户特征矩阵U*K
Q：初始化物品特征矩阵I*K
"""
# 评分矩阵R, 0 represents no comment now
R = np.array([[4, 0, 2, 0, 1],
              [0, 2, 3, 0, 0],
              [1, 0, 2, 4, 0],
              [5, 0, 0, 3, 1],
              [0, 0, 1, 5, 1],
              [0, 3, 2, 4, 1]])
K = 5
max_iter = 5000
alpha = 0.0002
lamda = 0.004

In [54]:
class Model:
    def __init__(self, max_iter, K, alpha, lamda):
        self.max_iter = max_iter
        self.K = K
        self.alpha = alpha
        self.lamda = lamda
        self.R = None
        self.cost = None

    def fit(self, R):
        # Define initial Pu and Qi
        U, I = R.shape[0], R.shape[1]
        P = np.random.rand(K, U)
        Q = np.random.rand(K, I)
        for _ in range(max_iter):
            for u in range(U):
                for i in range(I):
                    if R[u, i] > 0:
                        for k in range(K):
                            P[k, u] -= alpha * (2 * (P[:, u].T.dot(Q[:, i]) - R[u, i]) * Q[k, i] + 2 * lamda * P[k, u])
                            Q[k, i] -= alpha * (2 * (P[:, u].T.dot(Q[:, i]) - R[u, i]) * P[k, u] + 2 * lamda * Q[k, i])
            self.R = P.T.dot(Q)
            cost = 0
            for u in range(U):
                for i in range(I):
                    if R[u, i] > 0:
                        cost += (R[u, i] - self.R[u, i]) ** 2
                        for k in range(K):
                            cost += lamda * (P[k, u] ** 2 + Q[k, i] ** 2)
            self.cost = cost
            if cost < 0.0001:
                break

    def predict(self, u, i):
        return self.R[u, i]

In [55]:
model = Model(max_iter, K, alpha, lamda)
model.fit(R)
print(model.cost)
print(R)
print(model.R)

0.636830957374874
[[4 0 2 0 1]
 [0 2 3 0 0]
 [1 0 2 4 0]
 [5 0 0 3 1]
 [0 0 1 5 1]
 [0 3 2 4 1]]
[[3.94429859 2.85394241 2.11061946 4.53072925 0.95074413]
 [3.69596941 2.04322939 2.94335563 4.9471674  0.89976971]
 [1.04907149 1.69177091 1.85915096 4.02075158 0.58675171]
 [5.01053997 2.5417138  1.94696386 2.9805083  1.00811738]
 [2.05469811 2.86351048 1.16106149 4.91045894 1.05125539]
 [3.22002781 2.91942196 1.88983194 4.07846935 0.99914578]]


In [56]:
print(model.predict(0, 1))

2.8539424072767114
